### ISSUE TITLE
Digital dice roll

### ISSUE THREAD

**Issue by Apexal** [Daddy-s-Dungeons-Tools/ddtools-web#13]
We want to copy the effect that FoundryVTT and DNDBeyond have, shown here: https://www.youtube.com/watch?v=ajRUv30tfyA

From reading through forum posts, the DNDBeyond implementation actually runs a physics simulation right in the browser and determines the rolls based on the final result of the physics.

Let's explore what tools we would look at to implement this.

**Comment by zacharylove** [comment]
I saw this while looking for existing D&D projects a couple days ago: https://www.npmjs.com/package/@3d-dice/dice-box
It's a cool little animation that includes a physics simulation on a flat surface, like what you were talking about.

**Comment by Apexal** [comment]
PERFECT find. I don't know how I missed that myself. I spent a few hours looking at AMMO.js, Bullet.js, Three.js, etc. We should definitely use this.

**Comment by Apexal** [comment]
Latest version (literally released a few hours ago) of the aforementioned package is bork. I opened an [issue](https://github.com/3d-dice/dice-box/issues/41) and hopefully it'll get resolved soon.

**Comment by Apexal** [comment]
The developer fixed the package and I was able to successfully add it to the project. Unfortunately it lacks Typescript definitions so I had to also try to write my own TS declaration file that matches the package's API. Very fragile...
